---
version: "2"
run:
  build-tags:
    - trace

linters:
  default: all
  disable:
    - exhaustruct
    - wsl
    - noinlineerr
  settings:
    depguard:
      rules:
        repo-access:
          list-mode: lax
          files:
            - $all
            - "!${base-path}/internal/service/*"
            - "!${base-path}/internal/infra/**"
            - "!${base-path}/internal/cli/do.go"
          deny:
            - pkg: "gitlab.com/kabes/go-gpo/internal/infra"
              desc: "do not use infra directly"
        api:
          list-mode: lax
          files:
            - "{base-path}/internal/api/*"
          allow:
            - "gitlab.com/kabes/go-gpo/internal/model"
            - "gitlab.com/kabes/go-gpo/internal/service"
          deny:
            - pkg: "gitlab.com/kabes/go-gpo/internal/infra"
              desc: "do not use infra directly"
        db:
          list-mode: lax
          files:
            - $all
            - "!${base-path}/internal/cli/common.go"
            - "!${base-path}/internal/cli/do.go"
            - "!${base-path}/internal/cli/migrate.go"
            - "!${base-path}/internal/cli/serve.go"
            - "!${base-path}/internal/server/middlewares.go"
            - "!${base-path}/internal/infra/**"
            - "!${base-path}/internal/service/**"
          deny:
            - pkg: "gitlab.com/kabes/go-gpo/internal/db"
              desc: "do not use `db` directly"
    misspell:
      locale: US
      ignore-rules:
      # - xxx
    varnamelen:
      max-distance: 12
      ignore-names:
        - wg
        - rx
        - tx
        - re
        - ch
      ignore-decls:
        - t testing.T
        - T any
        - tr trace.Trace
        - w http.ResponseWriter
        - r *http.Request
        - db *sql.DB
    wrapcheck:
      ignore-sigs:
        - .Errorf(
        - errors.New(
        - errors.Unwrap(
        - .Wrap(
        - .Wrapf(
        - .WithMessage(
        - .WithMessagef(
        - .WithStack(
        - multierror.Append(
        - .ErrorOrNil()
        - errors.Join(
    wsl_v5:
      allow-first-in-block: true
      allow-whole-block: false
      branch-max-lines: 2
    tagliatelle:
      case:
        extended-rules:
          json:
            case: snake
    revive:
      rules:
        - name: var-naming
          arguments:
            - []
            - []
            - - skip-package-name-checks: true
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - .*_test.go$
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofumpt
    - golines
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$

  settings:
    gofumpt:
      # Choose whether to use the extra rules.
      # Default: false
      extra-rules: true
    golines:
      # Target maximum line length.
      # Default: 100
      max-len: 120
      # Shorten single-line comments.
      # Default: false
      shorten-comments: true
      # Default: true
      reformat-tags: false
