// Code generated by qtc from "basepage.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line internal/web/templates/basepage.qtpl:2
package templates

//line internal/web/templates/basepage.qtpl:2
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line internal/web/templates/basepage.qtpl:2
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line internal/web/templates/basepage.qtpl:3
type Page interface {
//line internal/web/templates/basepage.qtpl:3
	Title() string
//line internal/web/templates/basepage.qtpl:3
	StreamTitle(qw422016 *qt422016.Writer)
//line internal/web/templates/basepage.qtpl:3
	WriteTitle(qq422016 qtio422016.Writer)
//line internal/web/templates/basepage.qtpl:3
	Body(pctx *PageContext) string
//line internal/web/templates/basepage.qtpl:3
	StreamBody(qw422016 *qt422016.Writer, pctx *PageContext)
//line internal/web/templates/basepage.qtpl:3
	WriteBody(qq422016 qtio422016.Writer, pctx *PageContext)
//line internal/web/templates/basepage.qtpl:3
}

//line internal/web/templates/basepage.qtpl:9
func StreamPageTemplate(qw422016 *qt422016.Writer, p Page, pctx *PageContext) {
//line internal/web/templates/basepage.qtpl:9
	qw422016.N().S(`
<!doctype html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link rel="stylesheet" href="`)
//line internal/web/templates/basepage.qtpl:15
	qw422016.E().S(pctx.Webroot)
//line internal/web/templates/basepage.qtpl:15
	qw422016.N().S(`/web/static/main.css" type="text/css">
	`)
//line internal/web/templates/basepage.qtpl:16
	t := p.Title()

//line internal/web/templates/basepage.qtpl:16
	qw422016.N().S(`
	`)
//line internal/web/templates/basepage.qtpl:17
	if t != "" {
//line internal/web/templates/basepage.qtpl:17
		qw422016.N().S(`
	<title>go-gpo - `)
//line internal/web/templates/basepage.qtpl:18
		qw422016.E().S(t)
//line internal/web/templates/basepage.qtpl:18
		qw422016.N().S(`</title>
	`)
//line internal/web/templates/basepage.qtpl:19
	} else {
//line internal/web/templates/basepage.qtpl:19
		qw422016.N().S(`
	<title>go-gpo</title>
	`)
//line internal/web/templates/basepage.qtpl:21
	}
//line internal/web/templates/basepage.qtpl:21
	qw422016.N().S(`
</head>
<body>
	<header>
		<a href="`)
//line internal/web/templates/basepage.qtpl:25
	qw422016.E().S(pctx.Webroot)
//line internal/web/templates/basepage.qtpl:25
	qw422016.N().S(`/web/"><big><big>go-gpo</big></big></a>
		&emsp;
		<a href="`)
//line internal/web/templates/basepage.qtpl:27
	qw422016.E().S(pctx.Webroot)
//line internal/web/templates/basepage.qtpl:27
	qw422016.N().S(`/web/device/">Devices</a> |
		<a href="`)
//line internal/web/templates/basepage.qtpl:28
	qw422016.E().S(pctx.Webroot)
//line internal/web/templates/basepage.qtpl:28
	qw422016.N().S(`/web/podcast/">Podcasts</a> |
		<a href="`)
//line internal/web/templates/basepage.qtpl:29
	qw422016.E().S(pctx.Webroot)
//line internal/web/templates/basepage.qtpl:29
	qw422016.N().S(`/web/user/">User</a> |
		<a href="`)
//line internal/web/templates/basepage.qtpl:30
	qw422016.E().S(pctx.Webroot)
//line internal/web/templates/basepage.qtpl:30
	qw422016.N().S(`/web/auth/logout">Logout</a>
	</header>
	<br/>
	<content>

	`)
//line internal/web/templates/basepage.qtpl:35
	for _, f := range pctx.Flash() {
//line internal/web/templates/basepage.qtpl:35
		qw422016.N().S(`
		<div class="flash flash-`)
//line internal/web/templates/basepage.qtpl:36
		qw422016.E().S(f.Level)
//line internal/web/templates/basepage.qtpl:36
		qw422016.N().S(`">
			`)
//line internal/web/templates/basepage.qtpl:37
		if len(f.Messages) > 1 {
//line internal/web/templates/basepage.qtpl:37
			qw422016.N().S(`
				<ul>
					`)
//line internal/web/templates/basepage.qtpl:39
			for _, m := range f.Messages {
//line internal/web/templates/basepage.qtpl:39
				qw422016.N().S(`
						<li>`)
//line internal/web/templates/basepage.qtpl:40
				qw422016.E().S(m)
//line internal/web/templates/basepage.qtpl:40
				qw422016.N().S(`</li>
					`)
//line internal/web/templates/basepage.qtpl:41
			}
//line internal/web/templates/basepage.qtpl:41
			qw422016.N().S(`
				</ul>
			`)
//line internal/web/templates/basepage.qtpl:43
		} else {
//line internal/web/templates/basepage.qtpl:43
			qw422016.N().S(`
				<p>`)
//line internal/web/templates/basepage.qtpl:44
			qw422016.E().S(f.Messages[0])
//line internal/web/templates/basepage.qtpl:44
			qw422016.N().S(`</p>
			`)
//line internal/web/templates/basepage.qtpl:45
		}
//line internal/web/templates/basepage.qtpl:45
		qw422016.N().S(`
		</div>
	`)
//line internal/web/templates/basepage.qtpl:47
	}
//line internal/web/templates/basepage.qtpl:47
	qw422016.N().S(`

	`)
//line internal/web/templates/basepage.qtpl:49
	p.StreamBody(qw422016, pctx)
//line internal/web/templates/basepage.qtpl:49
	qw422016.N().S(`
	</content>
</body>
</html>
`)
//line internal/web/templates/basepage.qtpl:53
}

//line internal/web/templates/basepage.qtpl:53
func WritePageTemplate(qq422016 qtio422016.Writer, p Page, pctx *PageContext) {
//line internal/web/templates/basepage.qtpl:53
	qw422016 := qt422016.AcquireWriter(qq422016)
//line internal/web/templates/basepage.qtpl:53
	StreamPageTemplate(qw422016, p, pctx)
//line internal/web/templates/basepage.qtpl:53
	qt422016.ReleaseWriter(qw422016)
//line internal/web/templates/basepage.qtpl:53
}

//line internal/web/templates/basepage.qtpl:53
func PageTemplate(p Page, pctx *PageContext) string {
//line internal/web/templates/basepage.qtpl:53
	qb422016 := qt422016.AcquireByteBuffer()
//line internal/web/templates/basepage.qtpl:53
	WritePageTemplate(qb422016, p, pctx)
//line internal/web/templates/basepage.qtpl:53
	qs422016 := string(qb422016.B)
//line internal/web/templates/basepage.qtpl:53
	qt422016.ReleaseByteBuffer(qb422016)
//line internal/web/templates/basepage.qtpl:53
	return qs422016
//line internal/web/templates/basepage.qtpl:53
}

//line internal/web/templates/basepage.qtpl:56
type BasePage struct{}

//line internal/web/templates/basepage.qtpl:57
func (p *BasePage) StreamTitle(qw422016 *qt422016.Writer) {
//line internal/web/templates/basepage.qtpl:57
}

//line internal/web/templates/basepage.qtpl:57
func (p *BasePage) WriteTitle(qq422016 qtio422016.Writer) {
//line internal/web/templates/basepage.qtpl:57
	qw422016 := qt422016.AcquireWriter(qq422016)
//line internal/web/templates/basepage.qtpl:57
	p.StreamTitle(qw422016)
//line internal/web/templates/basepage.qtpl:57
	qt422016.ReleaseWriter(qw422016)
//line internal/web/templates/basepage.qtpl:57
}

//line internal/web/templates/basepage.qtpl:57
func (p *BasePage) Title() string {
//line internal/web/templates/basepage.qtpl:57
	qb422016 := qt422016.AcquireByteBuffer()
//line internal/web/templates/basepage.qtpl:57
	p.WriteTitle(qb422016)
//line internal/web/templates/basepage.qtpl:57
	qs422016 := string(qb422016.B)
//line internal/web/templates/basepage.qtpl:57
	qt422016.ReleaseByteBuffer(qb422016)
//line internal/web/templates/basepage.qtpl:57
	return qs422016
//line internal/web/templates/basepage.qtpl:57
}

//line internal/web/templates/basepage.qtpl:58
func (p *BasePage) StreamBody(qw422016 *qt422016.Writer, pctx *PageContext) {
//line internal/web/templates/basepage.qtpl:58
	qw422016.N().S(`body`)
//line internal/web/templates/basepage.qtpl:58
}

//line internal/web/templates/basepage.qtpl:58
func (p *BasePage) WriteBody(qq422016 qtio422016.Writer, pctx *PageContext) {
//line internal/web/templates/basepage.qtpl:58
	qw422016 := qt422016.AcquireWriter(qq422016)
//line internal/web/templates/basepage.qtpl:58
	p.StreamBody(qw422016, pctx)
//line internal/web/templates/basepage.qtpl:58
	qt422016.ReleaseWriter(qw422016)
//line internal/web/templates/basepage.qtpl:58
}

//line internal/web/templates/basepage.qtpl:58
func (p *BasePage) Body(pctx *PageContext) string {
//line internal/web/templates/basepage.qtpl:58
	qb422016 := qt422016.AcquireByteBuffer()
//line internal/web/templates/basepage.qtpl:58
	p.WriteBody(qb422016, pctx)
//line internal/web/templates/basepage.qtpl:58
	qs422016 := string(qb422016.B)
//line internal/web/templates/basepage.qtpl:58
	qt422016.ReleaseByteBuffer(qb422016)
//line internal/web/templates/basepage.qtpl:58
	return qs422016
//line internal/web/templates/basepage.qtpl:58
}
