// Code generated by qtc from "basepage.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line internal/web/templates/basepage.qtpl:2
package templates

//line internal/web/templates/basepage.qtpl:2
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line internal/web/templates/basepage.qtpl:2
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line internal/web/templates/basepage.qtpl:3
type Page interface {
//line internal/web/templates/basepage.qtpl:3
	Title() string
//line internal/web/templates/basepage.qtpl:3
	StreamTitle(qw422016 *qt422016.Writer)
//line internal/web/templates/basepage.qtpl:3
	WriteTitle(qq422016 qtio422016.Writer)
//line internal/web/templates/basepage.qtpl:3
	Body(pctx *PageContext) string
//line internal/web/templates/basepage.qtpl:3
	StreamBody(qw422016 *qt422016.Writer, pctx *PageContext)
//line internal/web/templates/basepage.qtpl:3
	WriteBody(qq422016 qtio422016.Writer, pctx *PageContext)
//line internal/web/templates/basepage.qtpl:3
}

//line internal/web/templates/basepage.qtpl:9
func StreamPageTemplate(qw422016 *qt422016.Writer, p Page, pctx *PageContext) {
//line internal/web/templates/basepage.qtpl:9
	qw422016.N().S(`
<!doctype html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link rel="stylesheet" href="/web/static/main.css" type="text/css">
	`)
//line internal/web/templates/basepage.qtpl:16
	t := p.Title()

//line internal/web/templates/basepage.qtpl:16
	qw422016.N().S(`
	`)
//line internal/web/templates/basepage.qtpl:17
	if t != "" {
//line internal/web/templates/basepage.qtpl:17
		qw422016.N().S(`
	<title>go-gpo - `)
//line internal/web/templates/basepage.qtpl:18
		qw422016.E().S(t)
//line internal/web/templates/basepage.qtpl:18
		qw422016.N().S(`</title>
	`)
//line internal/web/templates/basepage.qtpl:19
	} else {
//line internal/web/templates/basepage.qtpl:19
		qw422016.N().S(`
	<title>go-gpo</title>
	`)
//line internal/web/templates/basepage.qtpl:21
	}
//line internal/web/templates/basepage.qtpl:21
	qw422016.N().S(`
</head>
<body>
	<header>
		<a href="`)
//line internal/web/templates/basepage.qtpl:25
	qw422016.E().S(pctx.Webroot)
//line internal/web/templates/basepage.qtpl:25
	qw422016.N().S(`/web/"><big><big>go-gpo</big></big></a>
		&emsp;
		<a href="`)
//line internal/web/templates/basepage.qtpl:27
	qw422016.E().S(pctx.Webroot)
//line internal/web/templates/basepage.qtpl:27
	qw422016.N().S(`/web/device/">Devices</a> |
		<a href="`)
//line internal/web/templates/basepage.qtpl:28
	qw422016.E().S(pctx.Webroot)
//line internal/web/templates/basepage.qtpl:28
	qw422016.N().S(`/web/podcast/">Podcasts</a>
	</header>
	<br/>
	<content>
	`)
//line internal/web/templates/basepage.qtpl:32
	p.StreamBody(qw422016, pctx)
//line internal/web/templates/basepage.qtpl:32
	qw422016.N().S(`
	</content>
</body>
</html>
`)
//line internal/web/templates/basepage.qtpl:36
}

//line internal/web/templates/basepage.qtpl:36
func WritePageTemplate(qq422016 qtio422016.Writer, p Page, pctx *PageContext) {
//line internal/web/templates/basepage.qtpl:36
	qw422016 := qt422016.AcquireWriter(qq422016)
//line internal/web/templates/basepage.qtpl:36
	StreamPageTemplate(qw422016, p, pctx)
//line internal/web/templates/basepage.qtpl:36
	qt422016.ReleaseWriter(qw422016)
//line internal/web/templates/basepage.qtpl:36
}

//line internal/web/templates/basepage.qtpl:36
func PageTemplate(p Page, pctx *PageContext) string {
//line internal/web/templates/basepage.qtpl:36
	qb422016 := qt422016.AcquireByteBuffer()
//line internal/web/templates/basepage.qtpl:36
	WritePageTemplate(qb422016, p, pctx)
//line internal/web/templates/basepage.qtpl:36
	qs422016 := string(qb422016.B)
//line internal/web/templates/basepage.qtpl:36
	qt422016.ReleaseByteBuffer(qb422016)
//line internal/web/templates/basepage.qtpl:36
	return qs422016
//line internal/web/templates/basepage.qtpl:36
}

//line internal/web/templates/basepage.qtpl:39
type BasePage struct{}

//line internal/web/templates/basepage.qtpl:40
func (p *BasePage) StreamTitle(qw422016 *qt422016.Writer) {
//line internal/web/templates/basepage.qtpl:40
}

//line internal/web/templates/basepage.qtpl:40
func (p *BasePage) WriteTitle(qq422016 qtio422016.Writer) {
//line internal/web/templates/basepage.qtpl:40
	qw422016 := qt422016.AcquireWriter(qq422016)
//line internal/web/templates/basepage.qtpl:40
	p.StreamTitle(qw422016)
//line internal/web/templates/basepage.qtpl:40
	qt422016.ReleaseWriter(qw422016)
//line internal/web/templates/basepage.qtpl:40
}

//line internal/web/templates/basepage.qtpl:40
func (p *BasePage) Title() string {
//line internal/web/templates/basepage.qtpl:40
	qb422016 := qt422016.AcquireByteBuffer()
//line internal/web/templates/basepage.qtpl:40
	p.WriteTitle(qb422016)
//line internal/web/templates/basepage.qtpl:40
	qs422016 := string(qb422016.B)
//line internal/web/templates/basepage.qtpl:40
	qt422016.ReleaseByteBuffer(qb422016)
//line internal/web/templates/basepage.qtpl:40
	return qs422016
//line internal/web/templates/basepage.qtpl:40
}

//line internal/web/templates/basepage.qtpl:41
func (p *BasePage) StreamBody(qw422016 *qt422016.Writer, pctx *PageContext) {
//line internal/web/templates/basepage.qtpl:41
	qw422016.N().S(`body`)
//line internal/web/templates/basepage.qtpl:41
}

//line internal/web/templates/basepage.qtpl:41
func (p *BasePage) WriteBody(qq422016 qtio422016.Writer, pctx *PageContext) {
//line internal/web/templates/basepage.qtpl:41
	qw422016 := qt422016.AcquireWriter(qq422016)
//line internal/web/templates/basepage.qtpl:41
	p.StreamBody(qw422016, pctx)
//line internal/web/templates/basepage.qtpl:41
	qt422016.ReleaseWriter(qw422016)
//line internal/web/templates/basepage.qtpl:41
}

//line internal/web/templates/basepage.qtpl:41
func (p *BasePage) Body(pctx *PageContext) string {
//line internal/web/templates/basepage.qtpl:41
	qb422016 := qt422016.AcquireByteBuffer()
//line internal/web/templates/basepage.qtpl:41
	p.WriteBody(qb422016, pctx)
//line internal/web/templates/basepage.qtpl:41
	qs422016 := string(qb422016.B)
//line internal/web/templates/basepage.qtpl:41
	qt422016.ReleaseByteBuffer(qb422016)
//line internal/web/templates/basepage.qtpl:41
	return qs422016
//line internal/web/templates/basepage.qtpl:41
}
