// Code generated by qtc from "device_delete.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line internal/web/templates/device_delete.qtpl:1
package templates

//line internal/web/templates/device_delete.qtpl:1
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line internal/web/templates/device_delete.qtpl:1
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line internal/web/templates/device_delete.qtpl:2
type DeviceDeletePage struct {
	DeviceName string
}

//line internal/web/templates/device_delete.qtpl:7
func (p *DeviceDeletePage) StreamTitle(qw422016 *qt422016.Writer) {
//line internal/web/templates/device_delete.qtpl:7
	qw422016.N().S(`Device - delete`)
//line internal/web/templates/device_delete.qtpl:7
}

//line internal/web/templates/device_delete.qtpl:7
func (p *DeviceDeletePage) WriteTitle(qq422016 qtio422016.Writer) {
//line internal/web/templates/device_delete.qtpl:7
	qw422016 := qt422016.AcquireWriter(qq422016)
//line internal/web/templates/device_delete.qtpl:7
	p.StreamTitle(qw422016)
//line internal/web/templates/device_delete.qtpl:7
	qt422016.ReleaseWriter(qw422016)
//line internal/web/templates/device_delete.qtpl:7
}

//line internal/web/templates/device_delete.qtpl:7
func (p *DeviceDeletePage) Title() string {
//line internal/web/templates/device_delete.qtpl:7
	qb422016 := qt422016.AcquireByteBuffer()
//line internal/web/templates/device_delete.qtpl:7
	p.WriteTitle(qb422016)
//line internal/web/templates/device_delete.qtpl:7
	qs422016 := string(qb422016.B)
//line internal/web/templates/device_delete.qtpl:7
	qt422016.ReleaseByteBuffer(qb422016)
//line internal/web/templates/device_delete.qtpl:7
	return qs422016
//line internal/web/templates/device_delete.qtpl:7
}

//line internal/web/templates/device_delete.qtpl:9
func (p *DeviceDeletePage) StreamBody(qw422016 *qt422016.Writer, webroot string) {
//line internal/web/templates/device_delete.qtpl:9
	qw422016.N().S(`
<section>
	<h1>Delete device</h1>

	<form method="POST">
		<p>Delete device <em>`)
//line internal/web/templates/device_delete.qtpl:14
	qw422016.E().S(p.DeviceName)
//line internal/web/templates/device_delete.qtpl:14
	qw422016.N().S(`</em>?</p>
		<a href="`)
//line internal/web/templates/device_delete.qtpl:15
	qw422016.E().S(webroot)
//line internal/web/templates/device_delete.qtpl:15
	qw422016.N().S(`/web/device/">Back</a> <button type="submit">Delete</button>
	</form>
`)
//line internal/web/templates/device_delete.qtpl:17
}

//line internal/web/templates/device_delete.qtpl:17
func (p *DeviceDeletePage) WriteBody(qq422016 qtio422016.Writer, webroot string) {
//line internal/web/templates/device_delete.qtpl:17
	qw422016 := qt422016.AcquireWriter(qq422016)
//line internal/web/templates/device_delete.qtpl:17
	p.StreamBody(qw422016, webroot)
//line internal/web/templates/device_delete.qtpl:17
	qt422016.ReleaseWriter(qw422016)
//line internal/web/templates/device_delete.qtpl:17
}

//line internal/web/templates/device_delete.qtpl:17
func (p *DeviceDeletePage) Body(webroot string) string {
//line internal/web/templates/device_delete.qtpl:17
	qb422016 := qt422016.AcquireByteBuffer()
//line internal/web/templates/device_delete.qtpl:17
	p.WriteBody(qb422016, webroot)
//line internal/web/templates/device_delete.qtpl:17
	qs422016 := string(qb422016.B)
//line internal/web/templates/device_delete.qtpl:17
	qt422016.ReleaseByteBuffer(qb422016)
//line internal/web/templates/device_delete.qtpl:17
	return qs422016
//line internal/web/templates/device_delete.qtpl:17
}
