// Code generated by qtc from "devices.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line internal/web/templates/devices.qtpl:1
package templates

//line internal/web/templates/devices.qtpl:1
import "gitlab.com/kabes/go-gpo/internal/model"

//line internal/web/templates/devices.qtpl:3
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line internal/web/templates/devices.qtpl:3
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line internal/web/templates/devices.qtpl:4
type DevicesPage struct {
	Devices []model.Device
}

//line internal/web/templates/devices.qtpl:9
func (p *DevicesPage) StreamTitle(qw422016 *qt422016.Writer) {
//line internal/web/templates/devices.qtpl:9
	qw422016.N().S(`Devices`)
//line internal/web/templates/devices.qtpl:9
}

//line internal/web/templates/devices.qtpl:9
func (p *DevicesPage) WriteTitle(qq422016 qtio422016.Writer) {
//line internal/web/templates/devices.qtpl:9
	qw422016 := qt422016.AcquireWriter(qq422016)
//line internal/web/templates/devices.qtpl:9
	p.StreamTitle(qw422016)
//line internal/web/templates/devices.qtpl:9
	qt422016.ReleaseWriter(qw422016)
//line internal/web/templates/devices.qtpl:9
}

//line internal/web/templates/devices.qtpl:9
func (p *DevicesPage) Title() string {
//line internal/web/templates/devices.qtpl:9
	qb422016 := qt422016.AcquireByteBuffer()
//line internal/web/templates/devices.qtpl:9
	p.WriteTitle(qb422016)
//line internal/web/templates/devices.qtpl:9
	qs422016 := string(qb422016.B)
//line internal/web/templates/devices.qtpl:9
	qt422016.ReleaseByteBuffer(qb422016)
//line internal/web/templates/devices.qtpl:9
	return qs422016
//line internal/web/templates/devices.qtpl:9
}

//line internal/web/templates/devices.qtpl:11
func (p *DevicesPage) StreamBody(qw422016 *qt422016.Writer, pctx *PageContext) {
//line internal/web/templates/devices.qtpl:11
	qw422016.N().S(`
<section>
	<h1>Devices</h1>
	<table>
		<thead>
			<tr>
				<th>Name</th>
				<th>Type</th>
				<th>Caption</th>
				<th>&nbsp;</th>
			</tr>
		</thead>
		<tbody>
			`)
//line internal/web/templates/devices.qtpl:24
	for _, d := range p.Devices {
//line internal/web/templates/devices.qtpl:24
		qw422016.N().S(`
			<tr>
				<td>`)
//line internal/web/templates/devices.qtpl:26
		qw422016.E().S(d.Name)
//line internal/web/templates/devices.qtpl:26
		qw422016.N().S(`</td>
				<td>`)
//line internal/web/templates/devices.qtpl:27
		qw422016.E().S(d.DevType)
//line internal/web/templates/devices.qtpl:27
		qw422016.N().S(`</td>
				<td>`)
//line internal/web/templates/devices.qtpl:28
		qw422016.E().S(d.Caption)
//line internal/web/templates/devices.qtpl:28
		qw422016.N().S(`</td>
				<td><a href="`)
//line internal/web/templates/devices.qtpl:29
		qw422016.E().S(pctx.Webroot)
//line internal/web/templates/devices.qtpl:29
		qw422016.N().S(`/web/device/`)
//line internal/web/templates/devices.qtpl:29
		qw422016.E().S(d.Name)
//line internal/web/templates/devices.qtpl:29
		qw422016.N().S(`/delete">Delete</a></td>
			</tr>
			`)
//line internal/web/templates/devices.qtpl:31
	}
//line internal/web/templates/devices.qtpl:31
	qw422016.N().S(`
		</tbody>
	</table>
</section>


`)
//line internal/web/templates/devices.qtpl:37
}

//line internal/web/templates/devices.qtpl:37
func (p *DevicesPage) WriteBody(qq422016 qtio422016.Writer, pctx *PageContext) {
//line internal/web/templates/devices.qtpl:37
	qw422016 := qt422016.AcquireWriter(qq422016)
//line internal/web/templates/devices.qtpl:37
	p.StreamBody(qw422016, pctx)
//line internal/web/templates/devices.qtpl:37
	qt422016.ReleaseWriter(qw422016)
//line internal/web/templates/devices.qtpl:37
}

//line internal/web/templates/devices.qtpl:37
func (p *DevicesPage) Body(pctx *PageContext) string {
//line internal/web/templates/devices.qtpl:37
	qb422016 := qt422016.AcquireByteBuffer()
//line internal/web/templates/devices.qtpl:37
	p.WriteBody(qb422016, pctx)
//line internal/web/templates/devices.qtpl:37
	qs422016 := string(qb422016.B)
//line internal/web/templates/devices.qtpl:37
	qt422016.ReleaseByteBuffer(qb422016)
//line internal/web/templates/devices.qtpl:37
	return qs422016
//line internal/web/templates/devices.qtpl:37
}
