// Code generated by qtc from "episodes.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line internal/web/templates/episodes.qtpl:1
package templates

//line internal/web/templates/episodes.qtpl:1
import "gitlab.com/kabes/go-gpo/internal/model"

//line internal/web/templates/episodes.qtpl:3
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line internal/web/templates/episodes.qtpl:3
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line internal/web/templates/episodes.qtpl:4
type EpisodesPage struct {
	Episodes []model.Episode
}

//line internal/web/templates/episodes.qtpl:9
func (p *EpisodesPage) StreamTitle(qw422016 *qt422016.Writer) {
//line internal/web/templates/episodes.qtpl:9
	qw422016.N().S(`Episodes`)
//line internal/web/templates/episodes.qtpl:9
}

//line internal/web/templates/episodes.qtpl:9
func (p *EpisodesPage) WriteTitle(qq422016 qtio422016.Writer) {
//line internal/web/templates/episodes.qtpl:9
	qw422016 := qt422016.AcquireWriter(qq422016)
//line internal/web/templates/episodes.qtpl:9
	p.StreamTitle(qw422016)
//line internal/web/templates/episodes.qtpl:9
	qt422016.ReleaseWriter(qw422016)
//line internal/web/templates/episodes.qtpl:9
}

//line internal/web/templates/episodes.qtpl:9
func (p *EpisodesPage) Title() string {
//line internal/web/templates/episodes.qtpl:9
	qb422016 := qt422016.AcquireByteBuffer()
//line internal/web/templates/episodes.qtpl:9
	p.WriteTitle(qb422016)
//line internal/web/templates/episodes.qtpl:9
	qs422016 := string(qb422016.B)
//line internal/web/templates/episodes.qtpl:9
	qt422016.ReleaseByteBuffer(qb422016)
//line internal/web/templates/episodes.qtpl:9
	return qs422016
//line internal/web/templates/episodes.qtpl:9
}

//line internal/web/templates/episodes.qtpl:11
func (p *EpisodesPage) StreamBody(qw422016 *qt422016.Writer, webroot string) {
//line internal/web/templates/episodes.qtpl:11
	qw422016.N().S(`
<section>
  <h1>Episodes</h1>

  <table>
    <thead>
      <tr><th>Episode</th><th>Device</th><th>Action</th><th>Timestamp</th></tr>
    </thead>
    <tbody>
      `)
//line internal/web/templates/episodes.qtpl:20
	for _, e := range p.Episodes {
//line internal/web/templates/episodes.qtpl:20
		qw422016.N().S(`
      <tr>
        <td>`)
//line internal/web/templates/episodes.qtpl:22
		qw422016.E().S(e.URL)
//line internal/web/templates/episodes.qtpl:22
		qw422016.N().S(`</td>
        <td>`)
//line internal/web/templates/episodes.qtpl:23
		if e.Device != nil {
//line internal/web/templates/episodes.qtpl:23
			qw422016.E().S(e.Device.Name)
//line internal/web/templates/episodes.qtpl:23
		}
//line internal/web/templates/episodes.qtpl:23
		qw422016.N().S(`</td>
        <td>`)
//line internal/web/templates/episodes.qtpl:24
		qw422016.E().S(e.Action)
//line internal/web/templates/episodes.qtpl:24
		qw422016.N().S(`</td>
        <td>`)
//line internal/web/templates/episodes.qtpl:25
		qw422016.E().S(formatDateTime(e.Timestamp))
//line internal/web/templates/episodes.qtpl:25
		qw422016.N().S(`</td>
      </tr>
      `)
//line internal/web/templates/episodes.qtpl:27
	}
//line internal/web/templates/episodes.qtpl:27
	qw422016.N().S(`
    </tbody>
  </table>

</section>

`)
//line internal/web/templates/episodes.qtpl:33
}

//line internal/web/templates/episodes.qtpl:33
func (p *EpisodesPage) WriteBody(qq422016 qtio422016.Writer, webroot string) {
//line internal/web/templates/episodes.qtpl:33
	qw422016 := qt422016.AcquireWriter(qq422016)
//line internal/web/templates/episodes.qtpl:33
	p.StreamBody(qw422016, webroot)
//line internal/web/templates/episodes.qtpl:33
	qt422016.ReleaseWriter(qw422016)
//line internal/web/templates/episodes.qtpl:33
}

//line internal/web/templates/episodes.qtpl:33
func (p *EpisodesPage) Body(webroot string) string {
//line internal/web/templates/episodes.qtpl:33
	qb422016 := qt422016.AcquireByteBuffer()
//line internal/web/templates/episodes.qtpl:33
	p.WriteBody(qb422016, webroot)
//line internal/web/templates/episodes.qtpl:33
	qs422016 := string(qb422016.B)
//line internal/web/templates/episodes.qtpl:33
	qt422016.ReleaseByteBuffer(qb422016)
//line internal/web/templates/episodes.qtpl:33
	return qs422016
//line internal/web/templates/episodes.qtpl:33
}
