// Code generated by qtc from "error.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line internal/web/templates/error.qtpl:1
package templates

//line internal/web/templates/error.qtpl:1
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line internal/web/templates/error.qtpl:1
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line internal/web/templates/error.qtpl:2
type ErrorPage struct {
	Status  int
	Message string
	Details string
	ReqID   string
}

//line internal/web/templates/error.qtpl:10
func (p *ErrorPage) StreamTitle(qw422016 *qt422016.Writer) {
//line internal/web/templates/error.qtpl:10
	qw422016.N().S(`Error`)
//line internal/web/templates/error.qtpl:10
}

//line internal/web/templates/error.qtpl:10
func (p *ErrorPage) WriteTitle(qq422016 qtio422016.Writer) {
//line internal/web/templates/error.qtpl:10
	qw422016 := qt422016.AcquireWriter(qq422016)
//line internal/web/templates/error.qtpl:10
	p.StreamTitle(qw422016)
//line internal/web/templates/error.qtpl:10
	qt422016.ReleaseWriter(qw422016)
//line internal/web/templates/error.qtpl:10
}

//line internal/web/templates/error.qtpl:10
func (p *ErrorPage) Title() string {
//line internal/web/templates/error.qtpl:10
	qb422016 := qt422016.AcquireByteBuffer()
//line internal/web/templates/error.qtpl:10
	p.WriteTitle(qb422016)
//line internal/web/templates/error.qtpl:10
	qs422016 := string(qb422016.B)
//line internal/web/templates/error.qtpl:10
	qt422016.ReleaseByteBuffer(qb422016)
//line internal/web/templates/error.qtpl:10
	return qs422016
//line internal/web/templates/error.qtpl:10
}

//line internal/web/templates/error.qtpl:12
func (p *ErrorPage) StreamBody(qw422016 *qt422016.Writer, pctx *PageContext) {
//line internal/web/templates/error.qtpl:12
	qw422016.N().S(`
<section>
	<h2>Error</h2>
	<h3>`)
//line internal/web/templates/error.qtpl:15
	qw422016.E().S(p.Message)
//line internal/web/templates/error.qtpl:15
	qw422016.N().S(`</h3>
	`)
//line internal/web/templates/error.qtpl:16
	if p.Details != "" {
//line internal/web/templates/error.qtpl:16
		qw422016.N().S(`
	<p>`)
//line internal/web/templates/error.qtpl:17
		qw422016.E().S(p.Details)
//line internal/web/templates/error.qtpl:17
		qw422016.N().S(`</p>
	`)
//line internal/web/templates/error.qtpl:18
	}
//line internal/web/templates/error.qtpl:18
	qw422016.N().S(`
	`)
//line internal/web/templates/error.qtpl:19
	if p.ReqID != "" {
//line internal/web/templates/error.qtpl:19
		qw422016.N().S(`
	<p>reqid: `)
//line internal/web/templates/error.qtpl:20
		qw422016.E().S(p.ReqID)
//line internal/web/templates/error.qtpl:20
		qw422016.N().S(`</p>
	`)
//line internal/web/templates/error.qtpl:21
	}
//line internal/web/templates/error.qtpl:21
	qw422016.N().S(`
</section>

`)
//line internal/web/templates/error.qtpl:24
}

//line internal/web/templates/error.qtpl:24
func (p *ErrorPage) WriteBody(qq422016 qtio422016.Writer, pctx *PageContext) {
//line internal/web/templates/error.qtpl:24
	qw422016 := qt422016.AcquireWriter(qq422016)
//line internal/web/templates/error.qtpl:24
	p.StreamBody(qw422016, pctx)
//line internal/web/templates/error.qtpl:24
	qt422016.ReleaseWriter(qw422016)
//line internal/web/templates/error.qtpl:24
}

//line internal/web/templates/error.qtpl:24
func (p *ErrorPage) Body(pctx *PageContext) string {
//line internal/web/templates/error.qtpl:24
	qb422016 := qt422016.AcquireByteBuffer()
//line internal/web/templates/error.qtpl:24
	p.WriteBody(qb422016, pctx)
//line internal/web/templates/error.qtpl:24
	qs422016 := string(qb422016.B)
//line internal/web/templates/error.qtpl:24
	qt422016.ReleaseByteBuffer(qb422016)
//line internal/web/templates/error.qtpl:24
	return qs422016
//line internal/web/templates/error.qtpl:24
}
