// Code generated by qtc from "index.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line internal/web/templates/index.qtpl:1
package templates

//line internal/web/templates/index.qtpl:1
import "gitlab.com/kabes/go-gpo/internal/model"

//line internal/web/templates/index.qtpl:3
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line internal/web/templates/index.qtpl:3
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line internal/web/templates/index.qtpl:4
type IndexPage struct {
	LastActions []model.EpisodeLastAction
}

//line internal/web/templates/index.qtpl:9
func (p *IndexPage) StreamTitle(qw422016 *qt422016.Writer) {
//line internal/web/templates/index.qtpl:9
	qw422016.N().S(`Index`)
//line internal/web/templates/index.qtpl:9
}

//line internal/web/templates/index.qtpl:9
func (p *IndexPage) WriteTitle(qq422016 qtio422016.Writer) {
//line internal/web/templates/index.qtpl:9
	qw422016 := qt422016.AcquireWriter(qq422016)
//line internal/web/templates/index.qtpl:9
	p.StreamTitle(qw422016)
//line internal/web/templates/index.qtpl:9
	qt422016.ReleaseWriter(qw422016)
//line internal/web/templates/index.qtpl:9
}

//line internal/web/templates/index.qtpl:9
func (p *IndexPage) Title() string {
//line internal/web/templates/index.qtpl:9
	qb422016 := qt422016.AcquireByteBuffer()
//line internal/web/templates/index.qtpl:9
	p.WriteTitle(qb422016)
//line internal/web/templates/index.qtpl:9
	qs422016 := string(qb422016.B)
//line internal/web/templates/index.qtpl:9
	qt422016.ReleaseByteBuffer(qb422016)
//line internal/web/templates/index.qtpl:9
	return qs422016
//line internal/web/templates/index.qtpl:9
}

//line internal/web/templates/index.qtpl:11
func (p *IndexPage) StreamBody(qw422016 *qt422016.Writer, webroot string) {
//line internal/web/templates/index.qtpl:11
	qw422016.N().S(`
<section>
	<h2>User</h2>

	<ul>
		<li><a href="`)
//line internal/web/templates/index.qtpl:16
	qw422016.E().S(webroot)
//line internal/web/templates/index.qtpl:16
	qw422016.N().S(`/web/user/password">Change user password</a></li>
	</ul>
</section>

<br/><hr/>

<section>
	<h2>Last actions</h2>
	<table>
		<thead>
		<tr>
			<th>Timestamp</th>
			<th>Podcast</th>
			<th>Episode</th>
			<th>Device</th>
			<th>Action</th>
			<th>Started<br/>Position<br/>Total</th>
		</tr>
		</thead>
		<tbody>
		`)
//line internal/web/templates/index.qtpl:36
	for _, a := range p.LastActions {
//line internal/web/templates/index.qtpl:36
		qw422016.N().S(`
			<tr>
				<td>`)
//line internal/web/templates/index.qtpl:38
		qw422016.E().S(formatDateTime(a.Timestamp))
//line internal/web/templates/index.qtpl:38
		qw422016.N().S(`</td>
				<td>`)
//line internal/web/templates/index.qtpl:39
		qw422016.E().S(a.PodcastTitle)
//line internal/web/templates/index.qtpl:39
		qw422016.N().S(`<br/><small>`)
//line internal/web/templates/index.qtpl:39
		qw422016.E().S(a.PodcastURL)
//line internal/web/templates/index.qtpl:39
		qw422016.N().S(`</small></td>
				<td>`)
//line internal/web/templates/index.qtpl:40
		qw422016.E().S(a.Episode)
//line internal/web/templates/index.qtpl:40
		qw422016.N().S(`</td>
				<td>`)
//line internal/web/templates/index.qtpl:41
		qw422016.E().S(a.Device)
//line internal/web/templates/index.qtpl:41
		qw422016.N().S(`</td>
				<td>`)
//line internal/web/templates/index.qtpl:42
		qw422016.E().S(a.Action)
//line internal/web/templates/index.qtpl:42
		qw422016.N().S(`</td>
				<td>
				`)
//line internal/web/templates/index.qtpl:44
		if a.Action == "play" {
//line internal/web/templates/index.qtpl:44
			qw422016.N().S(`
					`)
//line internal/web/templates/index.qtpl:45
			qw422016.E().S(formatPInt32AsDuration(a.Started))
//line internal/web/templates/index.qtpl:45
			qw422016.N().S(`<br/> 
					`)
//line internal/web/templates/index.qtpl:46
			qw422016.E().S(formatPInt32AsDuration(a.Position))
//line internal/web/templates/index.qtpl:46
			qw422016.N().S(`<br/>
					`)
//line internal/web/templates/index.qtpl:47
			qw422016.E().S(formatPInt32AsDuration(a.Total))
//line internal/web/templates/index.qtpl:47
			qw422016.N().S(`
				`)
//line internal/web/templates/index.qtpl:48
		}
//line internal/web/templates/index.qtpl:48
		qw422016.N().S(`
				</td>
			</tr>
		`)
//line internal/web/templates/index.qtpl:51
	}
//line internal/web/templates/index.qtpl:51
	qw422016.N().S(`
		</tbody>
  </table>

</section>


`)
//line internal/web/templates/index.qtpl:58
}

//line internal/web/templates/index.qtpl:58
func (p *IndexPage) WriteBody(qq422016 qtio422016.Writer, webroot string) {
//line internal/web/templates/index.qtpl:58
	qw422016 := qt422016.AcquireWriter(qq422016)
//line internal/web/templates/index.qtpl:58
	p.StreamBody(qw422016, webroot)
//line internal/web/templates/index.qtpl:58
	qt422016.ReleaseWriter(qw422016)
//line internal/web/templates/index.qtpl:58
}

//line internal/web/templates/index.qtpl:58
func (p *IndexPage) Body(webroot string) string {
//line internal/web/templates/index.qtpl:58
	qb422016 := qt422016.AcquireByteBuffer()
//line internal/web/templates/index.qtpl:58
	p.WriteBody(qb422016, webroot)
//line internal/web/templates/index.qtpl:58
	qs422016 := string(qb422016.B)
//line internal/web/templates/index.qtpl:58
	qt422016.ReleaseByteBuffer(qb422016)
//line internal/web/templates/index.qtpl:58
	return qs422016
//line internal/web/templates/index.qtpl:58
}

// # vim:ft=mako:
