// Code generated by qtc from "index.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line internal/web/templates/index.qtpl:1
package templates

//line internal/web/templates/index.qtpl:1
import "gitlab.com/kabes/go-gpo/internal/model"

//line internal/web/templates/index.qtpl:3
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line internal/web/templates/index.qtpl:3
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line internal/web/templates/index.qtpl:4
type IndexPage struct {
	LastActions []model.EpisodeLastAction
}

//line internal/web/templates/index.qtpl:9
func (p *IndexPage) StreamTitle(qw422016 *qt422016.Writer) {
//line internal/web/templates/index.qtpl:9
	qw422016.N().S(`Index`)
//line internal/web/templates/index.qtpl:9
}

//line internal/web/templates/index.qtpl:9
func (p *IndexPage) WriteTitle(qq422016 qtio422016.Writer) {
//line internal/web/templates/index.qtpl:9
	qw422016 := qt422016.AcquireWriter(qq422016)
//line internal/web/templates/index.qtpl:9
	p.StreamTitle(qw422016)
//line internal/web/templates/index.qtpl:9
	qt422016.ReleaseWriter(qw422016)
//line internal/web/templates/index.qtpl:9
}

//line internal/web/templates/index.qtpl:9
func (p *IndexPage) Title() string {
//line internal/web/templates/index.qtpl:9
	qb422016 := qt422016.AcquireByteBuffer()
//line internal/web/templates/index.qtpl:9
	p.WriteTitle(qb422016)
//line internal/web/templates/index.qtpl:9
	qs422016 := string(qb422016.B)
//line internal/web/templates/index.qtpl:9
	qt422016.ReleaseByteBuffer(qb422016)
//line internal/web/templates/index.qtpl:9
	return qs422016
//line internal/web/templates/index.qtpl:9
}

//line internal/web/templates/index.qtpl:11
func (p *IndexPage) StreamBody(qw422016 *qt422016.Writer, pctx *PageContext) {
//line internal/web/templates/index.qtpl:11
	qw422016.N().S(`
<section>
	<h2>Last actions</h2>
	<table>
		<thead>
		<tr>
			<th>Timestamp</th>
			<th>Podcast</th>
			<th>Episode</th>
			<th>Device</th>
			<th>Action</th>
			<th>Started<br/>Position<br/>Total</th>
		</tr>
		</thead>
		<tbody>
		`)
//line internal/web/templates/index.qtpl:26
	for _, a := range p.LastActions {
//line internal/web/templates/index.qtpl:26
		qw422016.N().S(`
			<tr>
				<td>`)
//line internal/web/templates/index.qtpl:28
		qw422016.E().S(formatDateTime(a.Timestamp))
//line internal/web/templates/index.qtpl:28
		qw422016.N().S(`</td>
				<td>`)
//line internal/web/templates/index.qtpl:29
		if a.PodcastTitle != "" {
//line internal/web/templates/index.qtpl:29
			qw422016.E().S(a.PodcastTitle)
//line internal/web/templates/index.qtpl:29
		} else {
//line internal/web/templates/index.qtpl:29
			qw422016.N().S(`<small>`)
//line internal/web/templates/index.qtpl:29
			qw422016.E().S(a.PodcastURL)
//line internal/web/templates/index.qtpl:29
			qw422016.N().S(`</small>`)
//line internal/web/templates/index.qtpl:29
		}
//line internal/web/templates/index.qtpl:29
		qw422016.N().S(`</td>
				<td>`)
//line internal/web/templates/index.qtpl:30
		qw422016.E().S(a.Episode)
//line internal/web/templates/index.qtpl:30
		qw422016.N().S(`</td>
				<td>`)
//line internal/web/templates/index.qtpl:31
		qw422016.E().S(a.Device)
//line internal/web/templates/index.qtpl:31
		qw422016.N().S(`</td>
				<td>`)
//line internal/web/templates/index.qtpl:32
		qw422016.E().S(a.Action)
//line internal/web/templates/index.qtpl:32
		qw422016.N().S(`</td>
				<td>
				`)
//line internal/web/templates/index.qtpl:34
		if a.Action == "play" {
//line internal/web/templates/index.qtpl:34
			qw422016.N().S(`
					`)
//line internal/web/templates/index.qtpl:35
			qw422016.E().S(formatPInt32AsDuration(a.Started))
//line internal/web/templates/index.qtpl:35
			qw422016.N().S(`<br/>
					`)
//line internal/web/templates/index.qtpl:36
			qw422016.E().S(formatPInt32AsDuration(a.Position))
//line internal/web/templates/index.qtpl:36
			qw422016.N().S(`<br/>
					`)
//line internal/web/templates/index.qtpl:37
			qw422016.E().S(formatPInt32AsDuration(a.Total))
//line internal/web/templates/index.qtpl:37
			qw422016.N().S(`
				`)
//line internal/web/templates/index.qtpl:38
		}
//line internal/web/templates/index.qtpl:38
		qw422016.N().S(`
				</td>
			</tr>
		`)
//line internal/web/templates/index.qtpl:41
	}
//line internal/web/templates/index.qtpl:41
	qw422016.N().S(`
		</tbody>
	</table>
</section>


`)
//line internal/web/templates/index.qtpl:47
}

//line internal/web/templates/index.qtpl:47
func (p *IndexPage) WriteBody(qq422016 qtio422016.Writer, pctx *PageContext) {
//line internal/web/templates/index.qtpl:47
	qw422016 := qt422016.AcquireWriter(qq422016)
//line internal/web/templates/index.qtpl:47
	p.StreamBody(qw422016, pctx)
//line internal/web/templates/index.qtpl:47
	qt422016.ReleaseWriter(qw422016)
//line internal/web/templates/index.qtpl:47
}

//line internal/web/templates/index.qtpl:47
func (p *IndexPage) Body(pctx *PageContext) string {
//line internal/web/templates/index.qtpl:47
	qb422016 := qt422016.AcquireByteBuffer()
//line internal/web/templates/index.qtpl:47
	p.WriteBody(qb422016, pctx)
//line internal/web/templates/index.qtpl:47
	qs422016 := string(qb422016.B)
//line internal/web/templates/index.qtpl:47
	qt422016.ReleaseByteBuffer(qb422016)
//line internal/web/templates/index.qtpl:47
	return qs422016
//line internal/web/templates/index.qtpl:47
}
