// Code generated by qtc from "login.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line internal/web/templates/login.qtpl:3
package templates

//line internal/web/templates/login.qtpl:3
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line internal/web/templates/login.qtpl:3
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line internal/web/templates/login.qtpl:4
type LoginPage struct {
}

//line internal/web/templates/login.qtpl:8
func (l LoginPage) StreamBody(qw422016 *qt422016.Writer, pctx *PageContext) {
//line internal/web/templates/login.qtpl:8
	qw422016.N().S(`
<!doctype html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>go-gpo</title>
	<style>
		@media (prefers-color-scheme: dark){body {color:#fff;background:#000}}
		body{margin:1em auto;max-width:80em;padding:0 .62em;font:1.2em/1.62 sans-serif;}
		fieldset{margin:auto;max-width: 10em;padding: 1em;}
	</style>
</head>
<body>
	<content>
		<form method="POST">
			<fieldset>
				<legend>go-gpo</legend>
				<label for="login">Login:</label><br/>
				<input type="text" id="login" name="login"></input><br/>

				<label for="password">Password</label><br/>
				<input type="password" id="password" name="password"></input><br/>

				<button type="submit">Login</button>

			</fieldset>
		</form>
	</content>
</body>
</html>

`)
//line internal/web/templates/login.qtpl:40
}

//line internal/web/templates/login.qtpl:40
func (l LoginPage) WriteBody(qq422016 qtio422016.Writer, pctx *PageContext) {
//line internal/web/templates/login.qtpl:40
	qw422016 := qt422016.AcquireWriter(qq422016)
//line internal/web/templates/login.qtpl:40
	l.StreamBody(qw422016, pctx)
//line internal/web/templates/login.qtpl:40
	qt422016.ReleaseWriter(qw422016)
//line internal/web/templates/login.qtpl:40
}

//line internal/web/templates/login.qtpl:40
func (l LoginPage) Body(pctx *PageContext) string {
//line internal/web/templates/login.qtpl:40
	qb422016 := qt422016.AcquireByteBuffer()
//line internal/web/templates/login.qtpl:40
	l.WriteBody(qb422016, pctx)
//line internal/web/templates/login.qtpl:40
	qs422016 := string(qb422016.B)
//line internal/web/templates/login.qtpl:40
	qt422016.ReleaseByteBuffer(qb422016)
//line internal/web/templates/login.qtpl:40
	return qs422016
//line internal/web/templates/login.qtpl:40
}
