// Code generated by qtc from "logout.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line internal/web/templates/logout.qtpl:3
package templates

//line internal/web/templates/logout.qtpl:3
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line internal/web/templates/logout.qtpl:3
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line internal/web/templates/logout.qtpl:4
type LogoutPage struct {
}

//line internal/web/templates/logout.qtpl:8
func (l LogoutPage) StreamBody(qw422016 *qt422016.Writer, pctx *PageContext) {
//line internal/web/templates/logout.qtpl:8
	qw422016.N().S(`
<!doctype html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link rel="stylesheet" href="/web/static/main.css" type="text/css">
	<title>go-gpo</title>
</head>
<body>
	<content>
		<p><a href="`)
//line internal/web/templates/logout.qtpl:19
	qw422016.E().S(pctx.Webroot)
//line internal/web/templates/logout.qtpl:19
	qw422016.N().S(`/web/">Home</a></p>
	</content>
</body>
</html>

`)
//line internal/web/templates/logout.qtpl:24
}

//line internal/web/templates/logout.qtpl:24
func (l LogoutPage) WriteBody(qq422016 qtio422016.Writer, pctx *PageContext) {
//line internal/web/templates/logout.qtpl:24
	qw422016 := qt422016.AcquireWriter(qq422016)
//line internal/web/templates/logout.qtpl:24
	l.StreamBody(qw422016, pctx)
//line internal/web/templates/logout.qtpl:24
	qt422016.ReleaseWriter(qw422016)
//line internal/web/templates/logout.qtpl:24
}

//line internal/web/templates/logout.qtpl:24
func (l LogoutPage) Body(pctx *PageContext) string {
//line internal/web/templates/logout.qtpl:24
	qb422016 := qt422016.AcquireByteBuffer()
//line internal/web/templates/logout.qtpl:24
	l.WriteBody(qb422016, pctx)
//line internal/web/templates/logout.qtpl:24
	qs422016 := string(qb422016.B)
//line internal/web/templates/logout.qtpl:24
	qt422016.ReleaseByteBuffer(qb422016)
//line internal/web/templates/logout.qtpl:24
	return qs422016
//line internal/web/templates/logout.qtpl:24
}
