// Code generated by qtc from "podcast_delete.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line internal/web/templates/podcast_delete.qtpl:1
package templates

//line internal/web/templates/podcast_delete.qtpl:1
import "gitlab.com/kabes/go-gpo/internal/model"

//line internal/web/templates/podcast_delete.qtpl:3
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line internal/web/templates/podcast_delete.qtpl:3
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line internal/web/templates/podcast_delete.qtpl:4
type PodcastDeletePage struct {
	Podcast *model.Podcast
}

//line internal/web/templates/podcast_delete.qtpl:9
func (p *PodcastDeletePage) StreamTitle(qw422016 *qt422016.Writer) {
//line internal/web/templates/podcast_delete.qtpl:9
	qw422016.N().S(`Podcasts`)
//line internal/web/templates/podcast_delete.qtpl:9
}

//line internal/web/templates/podcast_delete.qtpl:9
func (p *PodcastDeletePage) WriteTitle(qq422016 qtio422016.Writer) {
//line internal/web/templates/podcast_delete.qtpl:9
	qw422016 := qt422016.AcquireWriter(qq422016)
//line internal/web/templates/podcast_delete.qtpl:9
	p.StreamTitle(qw422016)
//line internal/web/templates/podcast_delete.qtpl:9
	qt422016.ReleaseWriter(qw422016)
//line internal/web/templates/podcast_delete.qtpl:9
}

//line internal/web/templates/podcast_delete.qtpl:9
func (p *PodcastDeletePage) Title() string {
//line internal/web/templates/podcast_delete.qtpl:9
	qb422016 := qt422016.AcquireByteBuffer()
//line internal/web/templates/podcast_delete.qtpl:9
	p.WriteTitle(qb422016)
//line internal/web/templates/podcast_delete.qtpl:9
	qs422016 := string(qb422016.B)
//line internal/web/templates/podcast_delete.qtpl:9
	qt422016.ReleaseByteBuffer(qb422016)
//line internal/web/templates/podcast_delete.qtpl:9
	return qs422016
//line internal/web/templates/podcast_delete.qtpl:9
}

//line internal/web/templates/podcast_delete.qtpl:11
func (p *PodcastDeletePage) StreamBody(qw422016 *qt422016.Writer, pctx *PageContext) {
//line internal/web/templates/podcast_delete.qtpl:11
	qw422016.N().S(`
<section>
	<h1>Delete podcast</h1>

	<form method="POST">
		<p>Delete podcast
			<em>`)
//line internal/web/templates/podcast_delete.qtpl:17
	if p.Podcast.Title != "" {
//line internal/web/templates/podcast_delete.qtpl:17
		qw422016.E().S(p.Podcast.Title)
//line internal/web/templates/podcast_delete.qtpl:17
	} else {
//line internal/web/templates/podcast_delete.qtpl:17
		qw422016.E().S(p.Podcast.URL)
//line internal/web/templates/podcast_delete.qtpl:17
	}
//line internal/web/templates/podcast_delete.qtpl:17
	qw422016.N().S(`</em>?
			</p>
		<a href="`)
//line internal/web/templates/podcast_delete.qtpl:19
	qw422016.E().S(pctx.Webroot)
//line internal/web/templates/podcast_delete.qtpl:19
	qw422016.N().S(`/web/podcast/">Back</a> <button type="submit">Delete</button>
	</form>
</section>


`)
//line internal/web/templates/podcast_delete.qtpl:24
}

//line internal/web/templates/podcast_delete.qtpl:24
func (p *PodcastDeletePage) WriteBody(qq422016 qtio422016.Writer, pctx *PageContext) {
//line internal/web/templates/podcast_delete.qtpl:24
	qw422016 := qt422016.AcquireWriter(qq422016)
//line internal/web/templates/podcast_delete.qtpl:24
	p.StreamBody(qw422016, pctx)
//line internal/web/templates/podcast_delete.qtpl:24
	qt422016.ReleaseWriter(qw422016)
//line internal/web/templates/podcast_delete.qtpl:24
}

//line internal/web/templates/podcast_delete.qtpl:24
func (p *PodcastDeletePage) Body(pctx *PageContext) string {
//line internal/web/templates/podcast_delete.qtpl:24
	qb422016 := qt422016.AcquireByteBuffer()
//line internal/web/templates/podcast_delete.qtpl:24
	p.WriteBody(qb422016, pctx)
//line internal/web/templates/podcast_delete.qtpl:24
	qs422016 := string(qb422016.B)
//line internal/web/templates/podcast_delete.qtpl:24
	qt422016.ReleaseByteBuffer(qb422016)
//line internal/web/templates/podcast_delete.qtpl:24
	return qs422016
//line internal/web/templates/podcast_delete.qtpl:24
}

// # vim:ft=mako:ts=4:
