// Code generated by qtc from "podcasts.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line internal/web/templates/podcasts.qtpl:1
package templates

//line internal/web/templates/podcasts.qtpl:1
import "gitlab.com/kabes/go-gpo/internal/model"

//line internal/web/templates/podcasts.qtpl:3
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line internal/web/templates/podcasts.qtpl:3
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line internal/web/templates/podcasts.qtpl:4
type PodcastsPage struct {
	Podcasts       []model.PodcastWithLastEpisode
	SubscribedOnly bool
}

//line internal/web/templates/podcasts.qtpl:10
func (p *PodcastsPage) StreamTitle(qw422016 *qt422016.Writer) {
//line internal/web/templates/podcasts.qtpl:10
	qw422016.N().S(`Podcasts`)
//line internal/web/templates/podcasts.qtpl:10
}

//line internal/web/templates/podcasts.qtpl:10
func (p *PodcastsPage) WriteTitle(qq422016 qtio422016.Writer) {
//line internal/web/templates/podcasts.qtpl:10
	qw422016 := qt422016.AcquireWriter(qq422016)
//line internal/web/templates/podcasts.qtpl:10
	p.StreamTitle(qw422016)
//line internal/web/templates/podcasts.qtpl:10
	qt422016.ReleaseWriter(qw422016)
//line internal/web/templates/podcasts.qtpl:10
}

//line internal/web/templates/podcasts.qtpl:10
func (p *PodcastsPage) Title() string {
//line internal/web/templates/podcasts.qtpl:10
	qb422016 := qt422016.AcquireByteBuffer()
//line internal/web/templates/podcasts.qtpl:10
	p.WriteTitle(qb422016)
//line internal/web/templates/podcasts.qtpl:10
	qs422016 := string(qb422016.B)
//line internal/web/templates/podcasts.qtpl:10
	qt422016.ReleaseByteBuffer(qb422016)
//line internal/web/templates/podcasts.qtpl:10
	return qs422016
//line internal/web/templates/podcasts.qtpl:10
}

//line internal/web/templates/podcasts.qtpl:12
func (p *PodcastsPage) StreamBody(qw422016 *qt422016.Writer, pctx *PageContext) {
//line internal/web/templates/podcasts.qtpl:12
	qw422016.N().S(`
<section>
	<form method="POST">
		<fieldset>
			<legend>Add podcast</legend>
			<label>URL:</label> <input type="text" name="url" />
			<button type="submit">Add</button>
		</fieldset>
	</form>
</section>

<section>
	`)
//line internal/web/templates/podcasts.qtpl:24
	if p.SubscribedOnly {
//line internal/web/templates/podcasts.qtpl:24
		qw422016.N().S(`
		<h1>Subscribed podcasts</h1>
		<a href="`)
//line internal/web/templates/podcasts.qtpl:26
		qw422016.E().S(pctx.Webroot)
//line internal/web/templates/podcasts.qtpl:26
		qw422016.N().S(`/web/podcast/?showall">Show all podcasts</a>
	`)
//line internal/web/templates/podcasts.qtpl:27
	} else {
//line internal/web/templates/podcasts.qtpl:27
		qw422016.N().S(`
		<h1>All user podcasts</h1>
		<a href="`)
//line internal/web/templates/podcasts.qtpl:29
		qw422016.E().S(pctx.Webroot)
//line internal/web/templates/podcasts.qtpl:29
		qw422016.N().S(`/web/podcast/">Show subscribed only</a>
	`)
//line internal/web/templates/podcasts.qtpl:30
	}
//line internal/web/templates/podcasts.qtpl:30
	qw422016.N().S(`

	<table>
		<thead>
			<tr>
				<th>Title</th>
				<th>Description</th>
				<th>Last action date</th>
				<th>&nbsp;</th>
			</tr>
		</thead>
		<tbody>
			`)
//line internal/web/templates/podcasts.qtpl:42
	for _, po := range p.Podcasts {
//line internal/web/templates/podcasts.qtpl:42
		qw422016.N().S(`
				<tr>
					<td>
						<a href="`)
//line internal/web/templates/podcasts.qtpl:45
		qw422016.E().S(pctx.Webroot)
//line internal/web/templates/podcasts.qtpl:45
		qw422016.N().S(`/web/podcast/`)
//line internal/web/templates/podcasts.qtpl:45
		qw422016.N().D(int(po.PodcastID))
//line internal/web/templates/podcasts.qtpl:45
		qw422016.N().S(`/">
							`)
//line internal/web/templates/podcasts.qtpl:46
		if po.Title != "" {
//line internal/web/templates/podcasts.qtpl:46
			qw422016.E().S(po.Title)
//line internal/web/templates/podcasts.qtpl:46
		} else {
//line internal/web/templates/podcasts.qtpl:46
			qw422016.E().S(po.URL)
//line internal/web/templates/podcasts.qtpl:46
		}
//line internal/web/templates/podcasts.qtpl:46
		qw422016.N().S(`
						</a>
					</td>
					<td>
						`)
//line internal/web/templates/podcasts.qtpl:50
		if !po.Subscribed {
//line internal/web/templates/podcasts.qtpl:50
			qw422016.N().S(`<small><b>Not subscribed</b></small><br/>`)
//line internal/web/templates/podcasts.qtpl:50
		}
//line internal/web/templates/podcasts.qtpl:50
		qw422016.N().S(`
						`)
//line internal/web/templates/podcasts.qtpl:51
		qw422016.E().S(po.Description)
//line internal/web/templates/podcasts.qtpl:51
		qw422016.N().S(`
					</td>
					<td>
						`)
//line internal/web/templates/podcasts.qtpl:54
		if po.LastEpisode != nil {
//line internal/web/templates/podcasts.qtpl:54
			qw422016.N().S(`
							`)
//line internal/web/templates/podcasts.qtpl:55
			qw422016.E().S(formatDateTime(po.LastEpisode.Timestamp))
//line internal/web/templates/podcasts.qtpl:55
			qw422016.N().S(`
							(`)
//line internal/web/templates/podcasts.qtpl:56
			qw422016.E().S(po.LastEpisode.Action)
//line internal/web/templates/podcasts.qtpl:56
			qw422016.N().S(`)
						`)
//line internal/web/templates/podcasts.qtpl:57
		}
//line internal/web/templates/podcasts.qtpl:57
		qw422016.N().S(`
					</td>
					<td>
						`)
//line internal/web/templates/podcasts.qtpl:60
		if po.Website != "" {
//line internal/web/templates/podcasts.qtpl:60
			qw422016.N().S(`<a href="`)
//line internal/web/templates/podcasts.qtpl:60
			qw422016.E().S(po.Website)
//line internal/web/templates/podcasts.qtpl:60
			qw422016.N().S(`">Website</a><br/>`)
//line internal/web/templates/podcasts.qtpl:60
		}
//line internal/web/templates/podcasts.qtpl:60
		qw422016.N().S(`
						<a href="`)
//line internal/web/templates/podcasts.qtpl:61
		qw422016.E().S(pctx.Webroot)
//line internal/web/templates/podcasts.qtpl:61
		qw422016.N().S(`/web/episode/?podcast=`)
//line internal/web/templates/podcasts.qtpl:61
		qw422016.N().D(int(po.PodcastID))
//line internal/web/templates/podcasts.qtpl:61
		qw422016.N().S(`">Episodes</a>
					</td>
				</tr>
			`)
//line internal/web/templates/podcasts.qtpl:64
	}
//line internal/web/templates/podcasts.qtpl:64
	qw422016.N().S(`
		</tbody>
	</table>
</section>


`)
//line internal/web/templates/podcasts.qtpl:70
}

//line internal/web/templates/podcasts.qtpl:70
func (p *PodcastsPage) WriteBody(qq422016 qtio422016.Writer, pctx *PageContext) {
//line internal/web/templates/podcasts.qtpl:70
	qw422016 := qt422016.AcquireWriter(qq422016)
//line internal/web/templates/podcasts.qtpl:70
	p.StreamBody(qw422016, pctx)
//line internal/web/templates/podcasts.qtpl:70
	qt422016.ReleaseWriter(qw422016)
//line internal/web/templates/podcasts.qtpl:70
}

//line internal/web/templates/podcasts.qtpl:70
func (p *PodcastsPage) Body(pctx *PageContext) string {
//line internal/web/templates/podcasts.qtpl:70
	qb422016 := qt422016.AcquireByteBuffer()
//line internal/web/templates/podcasts.qtpl:70
	p.WriteBody(qb422016, pctx)
//line internal/web/templates/podcasts.qtpl:70
	qs422016 := string(qb422016.B)
//line internal/web/templates/podcasts.qtpl:70
	qt422016.ReleaseByteBuffer(qb422016)
//line internal/web/templates/podcasts.qtpl:70
	return qs422016
//line internal/web/templates/podcasts.qtpl:70
}
