// Code generated by qtc from "podcast.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line internal/web/templates/podcast.qtpl:1
package templates

//line internal/web/templates/podcast.qtpl:1
import "gitlab.com/kabes/go-gpo/internal/model"

//line internal/web/templates/podcast.qtpl:3
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line internal/web/templates/podcast.qtpl:3
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line internal/web/templates/podcast.qtpl:4
type PodcastPage struct {
	Podcast *model.Podcast
}

//line internal/web/templates/podcast.qtpl:9
func (p *PodcastPage) StreamTitle(qw422016 *qt422016.Writer) {
//line internal/web/templates/podcast.qtpl:9
	qw422016.N().S(`Podcasts`)
//line internal/web/templates/podcast.qtpl:9
}

//line internal/web/templates/podcast.qtpl:9
func (p *PodcastPage) WriteTitle(qq422016 qtio422016.Writer) {
//line internal/web/templates/podcast.qtpl:9
	qw422016 := qt422016.AcquireWriter(qq422016)
//line internal/web/templates/podcast.qtpl:9
	p.StreamTitle(qw422016)
//line internal/web/templates/podcast.qtpl:9
	qt422016.ReleaseWriter(qw422016)
//line internal/web/templates/podcast.qtpl:9
}

//line internal/web/templates/podcast.qtpl:9
func (p *PodcastPage) Title() string {
//line internal/web/templates/podcast.qtpl:9
	qb422016 := qt422016.AcquireByteBuffer()
//line internal/web/templates/podcast.qtpl:9
	p.WriteTitle(qb422016)
//line internal/web/templates/podcast.qtpl:9
	qs422016 := string(qb422016.B)
//line internal/web/templates/podcast.qtpl:9
	qt422016.ReleaseByteBuffer(qb422016)
//line internal/web/templates/podcast.qtpl:9
	return qs422016
//line internal/web/templates/podcast.qtpl:9
}

//line internal/web/templates/podcast.qtpl:11
func (p *PodcastPage) StreamBody(qw422016 *qt422016.Writer, webroot string) {
//line internal/web/templates/podcast.qtpl:11
	qw422016.N().S(`
<section>
	<h1>Podcast</h1>

	`)
//line internal/web/templates/podcast.qtpl:15
	if p.Podcast != nil {
//line internal/web/templates/podcast.qtpl:15
		qw422016.N().S(`
	<dl>
		<dt>Title<dt><dd>`)
//line internal/web/templates/podcast.qtpl:17
		qw422016.E().S(p.Podcast.Title)
//line internal/web/templates/podcast.qtpl:17
		qw422016.N().S(`</dd>
		<dt>URL<dt><dd>`)
//line internal/web/templates/podcast.qtpl:18
		qw422016.E().S(p.Podcast.URL)
//line internal/web/templates/podcast.qtpl:18
		qw422016.N().S(`</dd>
		<dt>Description<dt><dd>`)
//line internal/web/templates/podcast.qtpl:19
		qw422016.E().S(p.Podcast.Description)
//line internal/web/templates/podcast.qtpl:19
		qw422016.N().S(`</dd>
		<dt>Website<dt><dd>`)
//line internal/web/templates/podcast.qtpl:20
		qw422016.E().S(p.Podcast.Website)
//line internal/web/templates/podcast.qtpl:20
		qw422016.N().S(`</dd>
	</dl>
	`)
//line internal/web/templates/podcast.qtpl:22
	}
//line internal/web/templates/podcast.qtpl:22
	qw422016.N().S(`

	`)
//line internal/web/templates/podcast.qtpl:24
	if p.Podcast.Subscribed {
//line internal/web/templates/podcast.qtpl:24
		qw422016.N().S(`
	<form method="POST" action="unsubscribe">
		<button type="submit">Unsubscribe</button>
	</form>
	`)
//line internal/web/templates/podcast.qtpl:28
	} else {
//line internal/web/templates/podcast.qtpl:28
		qw422016.N().S(` 
	<form method="POST" action="resubscribe">
		<button type="submit">Subscribe again</button>
	</form>
	`)
//line internal/web/templates/podcast.qtpl:32
	}
//line internal/web/templates/podcast.qtpl:32
	qw422016.N().S(`
</section>


`)
//line internal/web/templates/podcast.qtpl:36
}

//line internal/web/templates/podcast.qtpl:36
func (p *PodcastPage) WriteBody(qq422016 qtio422016.Writer, webroot string) {
//line internal/web/templates/podcast.qtpl:36
	qw422016 := qt422016.AcquireWriter(qq422016)
//line internal/web/templates/podcast.qtpl:36
	p.StreamBody(qw422016, webroot)
//line internal/web/templates/podcast.qtpl:36
	qt422016.ReleaseWriter(qw422016)
//line internal/web/templates/podcast.qtpl:36
}

//line internal/web/templates/podcast.qtpl:36
func (p *PodcastPage) Body(webroot string) string {
//line internal/web/templates/podcast.qtpl:36
	qb422016 := qt422016.AcquireByteBuffer()
//line internal/web/templates/podcast.qtpl:36
	p.WriteBody(qb422016, webroot)
//line internal/web/templates/podcast.qtpl:36
	qs422016 := string(qb422016.B)
//line internal/web/templates/podcast.qtpl:36
	qt422016.ReleaseByteBuffer(qb422016)
//line internal/web/templates/podcast.qtpl:36
	return qs422016
//line internal/web/templates/podcast.qtpl:36
}

// # vim:ft=mako:ts=4:
