// Code generated by qtc from "users_change_password.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line internal/web/templates/users_change_password.qtpl:1
package templates

//line internal/web/templates/users_change_password.qtpl:1
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line internal/web/templates/users_change_password.qtpl:1
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line internal/web/templates/users_change_password.qtpl:2
type UsersChangePassPage struct {
	Msg string
}

//line internal/web/templates/users_change_password.qtpl:7
func (p *UsersChangePassPage) StreamTitle(qw422016 *qt422016.Writer) {
//line internal/web/templates/users_change_password.qtpl:7
	qw422016.N().S(`Change password`)
//line internal/web/templates/users_change_password.qtpl:7
}

//line internal/web/templates/users_change_password.qtpl:7
func (p *UsersChangePassPage) WriteTitle(qq422016 qtio422016.Writer) {
//line internal/web/templates/users_change_password.qtpl:7
	qw422016 := qt422016.AcquireWriter(qq422016)
//line internal/web/templates/users_change_password.qtpl:7
	p.StreamTitle(qw422016)
//line internal/web/templates/users_change_password.qtpl:7
	qt422016.ReleaseWriter(qw422016)
//line internal/web/templates/users_change_password.qtpl:7
}

//line internal/web/templates/users_change_password.qtpl:7
func (p *UsersChangePassPage) Title() string {
//line internal/web/templates/users_change_password.qtpl:7
	qb422016 := qt422016.AcquireByteBuffer()
//line internal/web/templates/users_change_password.qtpl:7
	p.WriteTitle(qb422016)
//line internal/web/templates/users_change_password.qtpl:7
	qs422016 := string(qb422016.B)
//line internal/web/templates/users_change_password.qtpl:7
	qt422016.ReleaseByteBuffer(qb422016)
//line internal/web/templates/users_change_password.qtpl:7
	return qs422016
//line internal/web/templates/users_change_password.qtpl:7
}

//line internal/web/templates/users_change_password.qtpl:9
func (p *UsersChangePassPage) StreamBody(qw422016 *qt422016.Writer, webroot string) {
//line internal/web/templates/users_change_password.qtpl:9
	qw422016.N().S(`
<section>
	<h1>Change password</h1>
	`)
//line internal/web/templates/users_change_password.qtpl:12
	if p.Msg != "" {
//line internal/web/templates/users_change_password.qtpl:12
		qw422016.N().S(`
		<p><b>`)
//line internal/web/templates/users_change_password.qtpl:13
		qw422016.E().S(p.Msg)
//line internal/web/templates/users_change_password.qtpl:13
		qw422016.N().S(`</b></p>
	`)
//line internal/web/templates/users_change_password.qtpl:14
	}
//line internal/web/templates/users_change_password.qtpl:14
	qw422016.N().S(`

	<form method="post">
		<p><label>Current password: <input name="cpass" type="password"></label></p>
		<p><label>New password: <input name="npass1" type="password"></label></p>
		<p><label>New password again: <input name="npass2" type="password"></label></p>
		<p><button type="submit">Change</button></p>
	</form>
</section>


`)
//line internal/web/templates/users_change_password.qtpl:25
}

//line internal/web/templates/users_change_password.qtpl:25
func (p *UsersChangePassPage) WriteBody(qq422016 qtio422016.Writer, webroot string) {
//line internal/web/templates/users_change_password.qtpl:25
	qw422016 := qt422016.AcquireWriter(qq422016)
//line internal/web/templates/users_change_password.qtpl:25
	p.StreamBody(qw422016, webroot)
//line internal/web/templates/users_change_password.qtpl:25
	qt422016.ReleaseWriter(qw422016)
//line internal/web/templates/users_change_password.qtpl:25
}

//line internal/web/templates/users_change_password.qtpl:25
func (p *UsersChangePassPage) Body(webroot string) string {
//line internal/web/templates/users_change_password.qtpl:25
	qb422016 := qt422016.AcquireByteBuffer()
//line internal/web/templates/users_change_password.qtpl:25
	p.WriteBody(qb422016, webroot)
//line internal/web/templates/users_change_password.qtpl:25
	qs422016 := string(qb422016.B)
//line internal/web/templates/users_change_password.qtpl:25
	qt422016.ReleaseByteBuffer(qb422016)
//line internal/web/templates/users_change_password.qtpl:25
	return qs422016
//line internal/web/templates/users_change_password.qtpl:25
}

// # vim:ft=mako:ts=4:
