// Code generated by qtc from "user.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line internal/web/templates/user.qtpl:1
package templates

//line internal/web/templates/user.qtpl:1
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line internal/web/templates/user.qtpl:1
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line internal/web/templates/user.qtpl:2
type UserPage struct {
}

//line internal/web/templates/user.qtpl:6
func (p *UserPage) StreamTitle(qw422016 *qt422016.Writer) {
//line internal/web/templates/user.qtpl:6
	qw422016.N().S(`Change password`)
//line internal/web/templates/user.qtpl:6
}

//line internal/web/templates/user.qtpl:6
func (p *UserPage) WriteTitle(qq422016 qtio422016.Writer) {
//line internal/web/templates/user.qtpl:6
	qw422016 := qt422016.AcquireWriter(qq422016)
//line internal/web/templates/user.qtpl:6
	p.StreamTitle(qw422016)
//line internal/web/templates/user.qtpl:6
	qt422016.ReleaseWriter(qw422016)
//line internal/web/templates/user.qtpl:6
}

//line internal/web/templates/user.qtpl:6
func (p *UserPage) Title() string {
//line internal/web/templates/user.qtpl:6
	qb422016 := qt422016.AcquireByteBuffer()
//line internal/web/templates/user.qtpl:6
	p.WriteTitle(qb422016)
//line internal/web/templates/user.qtpl:6
	qs422016 := string(qb422016.B)
//line internal/web/templates/user.qtpl:6
	qt422016.ReleaseByteBuffer(qb422016)
//line internal/web/templates/user.qtpl:6
	return qs422016
//line internal/web/templates/user.qtpl:6
}

//line internal/web/templates/user.qtpl:8
func (p *UserPage) StreamBody(qw422016 *qt422016.Writer, pctx *PageContext) {
//line internal/web/templates/user.qtpl:8
	qw422016.N().S(`
<section>
	<h2>User</h2>

	<ul>
		<li><a href="`)
//line internal/web/templates/user.qtpl:13
	qw422016.E().S(pctx.Webroot)
//line internal/web/templates/user.qtpl:13
	qw422016.N().S(`/web/user/password">Change user password</a></li>
	</ul>
</section>


`)
//line internal/web/templates/user.qtpl:18
}

//line internal/web/templates/user.qtpl:18
func (p *UserPage) WriteBody(qq422016 qtio422016.Writer, pctx *PageContext) {
//line internal/web/templates/user.qtpl:18
	qw422016 := qt422016.AcquireWriter(qq422016)
//line internal/web/templates/user.qtpl:18
	p.StreamBody(qw422016, pctx)
//line internal/web/templates/user.qtpl:18
	qt422016.ReleaseWriter(qw422016)
//line internal/web/templates/user.qtpl:18
}

//line internal/web/templates/user.qtpl:18
func (p *UserPage) Body(pctx *PageContext) string {
//line internal/web/templates/user.qtpl:18
	qb422016 := qt422016.AcquireByteBuffer()
//line internal/web/templates/user.qtpl:18
	p.WriteBody(qb422016, pctx)
//line internal/web/templates/user.qtpl:18
	qs422016 := string(qb422016.B)
//line internal/web/templates/user.qtpl:18
	qt422016.ReleaseByteBuffer(qb422016)
//line internal/web/templates/user.qtpl:18
	return qs422016
//line internal/web/templates/user.qtpl:18
}
