// Code generated by qtc from "user_change_password.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line internal/web/templates/user_change_password.qtpl:1
package templates

//line internal/web/templates/user_change_password.qtpl:1
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line internal/web/templates/user_change_password.qtpl:1
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line internal/web/templates/user_change_password.qtpl:2
type UserChangePassPage struct {
}

//line internal/web/templates/user_change_password.qtpl:6
func (p *UserChangePassPage) StreamTitle(qw422016 *qt422016.Writer) {
//line internal/web/templates/user_change_password.qtpl:6
	qw422016.N().S(`Change password`)
//line internal/web/templates/user_change_password.qtpl:6
}

//line internal/web/templates/user_change_password.qtpl:6
func (p *UserChangePassPage) WriteTitle(qq422016 qtio422016.Writer) {
//line internal/web/templates/user_change_password.qtpl:6
	qw422016 := qt422016.AcquireWriter(qq422016)
//line internal/web/templates/user_change_password.qtpl:6
	p.StreamTitle(qw422016)
//line internal/web/templates/user_change_password.qtpl:6
	qt422016.ReleaseWriter(qw422016)
//line internal/web/templates/user_change_password.qtpl:6
}

//line internal/web/templates/user_change_password.qtpl:6
func (p *UserChangePassPage) Title() string {
//line internal/web/templates/user_change_password.qtpl:6
	qb422016 := qt422016.AcquireByteBuffer()
//line internal/web/templates/user_change_password.qtpl:6
	p.WriteTitle(qb422016)
//line internal/web/templates/user_change_password.qtpl:6
	qs422016 := string(qb422016.B)
//line internal/web/templates/user_change_password.qtpl:6
	qt422016.ReleaseByteBuffer(qb422016)
//line internal/web/templates/user_change_password.qtpl:6
	return qs422016
//line internal/web/templates/user_change_password.qtpl:6
}

//line internal/web/templates/user_change_password.qtpl:8
func (p *UserChangePassPage) StreamBody(qw422016 *qt422016.Writer, pctx *PageContext) {
//line internal/web/templates/user_change_password.qtpl:8
	qw422016.N().S(`
<section>
	<h1>Change password</h1>

	<form method="post">
		<fieldset>
		<p><label>Current password:</label> <input name="cpass" type="password"></p>
		<p><label>New password:</label> <input name="npass1" type="password"></p>
		<p><label>New password again:</label> <input name="npass2" type="password"></p>
		<p><button type="submit">Change</button></p>
		</fieldset>
	</form>
</section>


`)
//line internal/web/templates/user_change_password.qtpl:23
}

//line internal/web/templates/user_change_password.qtpl:23
func (p *UserChangePassPage) WriteBody(qq422016 qtio422016.Writer, pctx *PageContext) {
//line internal/web/templates/user_change_password.qtpl:23
	qw422016 := qt422016.AcquireWriter(qq422016)
//line internal/web/templates/user_change_password.qtpl:23
	p.StreamBody(qw422016, pctx)
//line internal/web/templates/user_change_password.qtpl:23
	qt422016.ReleaseWriter(qw422016)
//line internal/web/templates/user_change_password.qtpl:23
}

//line internal/web/templates/user_change_password.qtpl:23
func (p *UserChangePassPage) Body(pctx *PageContext) string {
//line internal/web/templates/user_change_password.qtpl:23
	qb422016 := qt422016.AcquireByteBuffer()
//line internal/web/templates/user_change_password.qtpl:23
	p.WriteBody(qb422016, pctx)
//line internal/web/templates/user_change_password.qtpl:23
	qs422016 := string(qb422016.B)
//line internal/web/templates/user_change_password.qtpl:23
	qt422016.ReleaseByteBuffer(qb422016)
//line internal/web/templates/user_change_password.qtpl:23
	return qs422016
//line internal/web/templates/user_change_password.qtpl:23
}
